# Find openjpeg2 library
#
#  LIBOPENJPEG2_INCLUDE_DIRS - where to find openjpeg2.h, etc
#  LIBOPENJPEG2_LIBRARIES    - Lists of libraries when using openjpeg2
#  LIBOPENJPEG2_FOUND        - True if openjpeg2 found

INCLUDE(FindPackageHandleStandardArgs)

SET(LIBOPENJPEG2_DIR "${DCMTK_SOURCE_DIR}/third-party/openjpeg2")
SET(LIBOPENJPEG2_INCLUDE_DIR "${LIBOPENJPEG2_DIR}/include" CACHE PATH
  "Path to OpenJPEG 2.x include directory")

ADD_DEFINITIONS("-DOPJ_STATIC")

SET(LIBOPENJPEG2_LIBDIR "${LIBOPENJPEG2_DIR}/lib")
SET(LIBOPENJPEG2_LIBRARY "${LIBOPENJPEG2_LIBDIR}/libopenjp2.a" CACHE FILEPATH
  "Path to OpenJPEG 2.x library")

MARK_AS_ADVANCED(LIBOPENJPEG2_INCLUDE_DIR)
MARK_AS_ADVANCED(LIBOPENJPEG2_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENJPEG2
  REQUIRED_VARS LIBOPENJPEG2_INCLUDE_DIR LIBOPENJPEG2_LIBRARY)
